spring:
  profiles:
    active: secret
  jackson:
    property-naming-strategy: SNAKE_CASE
  jwt:
    secret: bangcutsoragodoongmeruohboksayif

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  port: 7777

openvidu:
  url: http://i11e107.p.ssafy.io:4443
  secret: bangcutsoragodoongmeruohboksayif

logging:
  level:
    org.springframework.core.env: DEBUG