spring:
  profiles:
    active: secret
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jwt:
    secret: bangcutsoragodoongmeruohboksayif

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  port: 8080

openvidu:
  url: https://i11e107.p.ssafy.io:4443
  secret: bangcutsoragodoongmeruohboksayif

logging:
  level:
    org.springframework.core.env: DEBUG