spring:
  profiles:
    include: secret
  jackson:
    property-naming-strategy: SNAKE_CASE
  jwt:
    secret: bangcutsoragodoongmeruohboksayif

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  port: 9090

openvidu:
  url: http://localhost:4443
  secret: bangcutsoragodoongmeruohboksayif