version: '3'
services:
  backend:
    image: leechanghojjang/sayif-backend:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sayif-mysql:3306/sayif
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sayif
    networks:
      - sayif_default

  frontend:
    image: leechanghojjang/sayif-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - sayif_default

networks:
  sayif_default:
    external: true