version: '3'
services:
  backend:
    image: leechanghojjang/sayif-backend:latest
    build:
      context: ./backend/sayif
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - sayif_default
  
  frontend:
    image: leechanghojjang/sayif-frontend:latest
    build:
      context: ./frontend/sayif
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - sayif_default
networks:
  sayif_default:
    external: true