version: '3'
services:
  backend:
    image: leechanghojjang/sayif-backend:latest
    ports:
      - "9090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://i11e107.p.ssafy.io:3306/sayif
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sayif
    networks:
      - sayif_default

  frontend:
    image: leechanghojjang/sayif-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - sayif_default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서를 로컬에서 사용
    depends_on:
      - frontend
      - backend
    networks:
      - sayif_default

networks:
  sayif_default:
    external: true